version: "2.1"

services:
  server:
    container_name: server
    build: .
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "3000:3000"
  database:
  image: postgres
  ports:
    - "3000:3000"
  command: --init-file /data/application/init.sql
  volumes:
    - ./init.sql:/data/application/init.sql
  environment:
    PGHOST: localhost
    PGDATABASE: User
    PGUSER: db_user
    PGPASSWORD: db_password
    PGPORT: 3000
      secret# TODO: FINISH

